trigger:
- main

pool: todoapp

stages:
- stage: MyFirstStage
  jobs:
  - job: BuildJob
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTask@5
      displayName: "Terraform init"
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Infra_automation'
        backendServiceArm: 'practice'
        backendAzureRmResourceGroupName: 'rg-web'
        backendAzureRmStorageAccountName: 'bhumistg'
        backendAzureRmContainerName: 'mussorie'
        backendAzureRmKey: 'terraform.tfstate'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Infra_automation'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Infra_automation'
        environmentServiceNameAzureRM: 'practice'

- stage: MySecondJob
  dependsOn: MyFirstStage
  jobs:
  - job: Terraformapply
    steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Infra_automation'
        backendServiceArm: 'practice'
        backendAzureRmResourceGroupName: 'rg-web'
        backendAzureRmStorageAccountName: 'bhumistg'
        backendAzureRmContainerName: 'mussorie'
        backendAzureRmKey: 'terraform.tfstate'
    - task: AzureCLI@2
      displayName: "Terraform Import RG"
      inputs:
        azureSubscription: 'practice'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          cd $(System.DefaultWorkingDirectory)/Infra_automation

          terraform init

          terraform import module.resource_group.azurerm_resource_group.resource_group["rg1"] \
          /subscriptions/4ff5875c-9724-4b2e-8ac9-3c94a8388c9a/resourceGroups/rg-web || true    
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Infra_automation'
        environmentServiceNameAzureRM: 'practice'