trigger: 
- main 

pool: todoapp

steps:
- task: TerraformInstaller@1
  displayName: "Terraform install"
  inputs:
    terraformVersion: 'latest'
- task: TerraformTask@5
  displayName: "terraform init"
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Infra_automation'
    backendServiceArm: 'practice'
    backendAzureRmResourceGroupName: 'rg-web'
    backendAzureRmStorageAccountName: 'bhumistg'
    backendAzureRmContainerName: 'mussorie'
    backendAzureRmKey: 'terraform.tfsate'